### PR TITLE
CLI generate enum with numeric like variants

### LINKED ISSUE #579: sea-orm-cli: Ident cannot be a number
## Description

Error reported with `sea-orm-cli` when there is one of the Enum variant is of integer / number in the sql table.

## Steps to Reproduce

Error reporeted when `'k1','k2'` changed to `'1', '2'`
image

image

### Expected Behavior

no errors

### Actual Behavior

image

### Reproduces How Often

always 

## Versions

image

## Additional Information

no

### PR DESCRIPTION
**Pull request by billy1624**
## PR Info

- Closes #579

## Fixes

- When generating `ActiveEnum` with number like variants. Those variants can't be formatted as Rust identifier. This can be fixed by add an `_` before the number like variants.

The SQL of Enum type.

```sql
create type tea as enum ('1', '2');
```

The generated `ActiveEnum`

```rs
//! SeaORM Entity. Generated by sea-orm-codegen 0.6.0

use sea_orm::entity::prelude::*;

#[derive(Debug, Clone, PartialEq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "tea")]
pub enum Tea {
    #[sea_orm(string_value = "1")]
    _1,
    #[sea_orm(string_value = "2")]
    _2,
}
```

### CODE REVIEW

**Comment by billy1624** [comment]
Hey @yb3616, you can try it by cloning the branch. Then, `cd` into `sea-orm/sea-orm-cli` folder. Finally, run the `sea-orm-cli` with the following command

```
cargo r -- generate entity --database-url postgres://root:root@localhost/active_enum_tests -o output_folder
```

**Comment by tyt2y3** [comment]
@yb3616 what is your use case for this? Isn't it strange to use a enum with numeric variants?

File: sea-orm-codegen/src/entity/active_enum.rs [hunk 1]
```diff
@@ -14,10 +14,13 @@ impl ActiveEnum {
         let enum_name = &self.enum_name;
         let enum_iden = format_ident!("{}", enum_name.to_camel_case());
         let values = &self.values;
-        let variants = self
-            .values
-            .iter()
-            .map(|v| format_ident!("{}", v.to_camel_case()));
+        let variants = self.values.iter().map(|v| v.trim()).map(|v| {
+            if v.chars().all(|c| c.is_numeric()) {
```
Comment (tyt2y3) [inline sea-orm-codegen/src/entity/active_enum.rs:18]: https://github.com/SeaQL/sea-orm/issues/1172 may be 'starts_with numeric'?

Comment (billy1624) [reply sea-orm-codegen/src/entity/active_enum.rs:18]: Fixed on https://github.com/SeaQL/sea-orm/pull/1211
