### PR TITLE
Don't call last_insert_id if not needed

### LINKED ISSUE #1357: Hitting 'negative last_insert_rowid' panic with Sqlite
## Description

I have a table with a primary ID that is a hash, stored as a signed integer (since unsigned 64 bit is not supported). Auto-increment is turned off for that table.
When storing a new element, if the hash as signed is negative, then sea-orm panics on that line: https://github.com/SeaQL/sea-orm/blob/master/src/executor/execute.rs#L43

## Steps to Reproduce

- Create an SQlite table with an i64 primary key: https://github.com/nitnelave/lldap/blob/c64d32e2c0cc698c61ca40e8364ab0cd7934cd46/server/src/domain/model/jwt_refresh_storage.rs#L12
- Insert a negative value.

### Expected Behavior

Since auto-increment is turned off for that table, `last_insert_id` should probably not be called to avoid a panic.

### Actual Behavior

Panic.

### Reproduces How Often

Always.

## Versions

Using sea-orm 0.10.3 (no other version override). Running on alpine, using the bundled Sqlite.

## Additional Information

The query, for reference: https://github.com/nitnelave/lldap/blob/c64d32e2c0cc698c61ca40e8364ab0cd7934cd46/server/src/infra/sql_backend_handler.rs#L49

### PR DESCRIPTION
**Pull request by tyt2y3**
Fixes #1357

### CODE REVIEW

File: src/executor/insert.rs [hunk 1]
```diff
@@ -137,29 +138,49 @@ where
...
+    }
+
+    let insert_result = if db.support_returning() {
+        let mut rows = db.query_all(statement).await?;
+        if rows.is_empty() {
+            return Err(DbErr::RecordNotInserted(
+                "None of the records are being inserted".to_owned(),
+            ));
         }
+        QueryOrExecResult::Query(rows.remove(rows.len() - 1))
```
Comment (nitnelave) [inline src/executor/insert.rs:154]: `rows.pop().unwrap()`?

File: src/executor/insert.rs [hunk 2]
```diff
@@ -137,29 +138,49 @@ where
...
-            let res = rows.last().ok_or_else(|| {
-                DbErr::RecordNotInserted("None of the records are being inserted".to_owned())
-            })?;
-            res.try_get_many("", cols.as_ref()).ok()
-        }
-        false => {
-            let last_insert_id = db.execute(statement).await?.last_insert_id();
-            ValueTypeOf::<A>::try_from_u64(last_insert_id).ok()
+
+    enum QueryOrExecResult {
```
Comment (nitnelave) [inline src/executor/insert.rs:142]: It's quite awkward to have an enum where you already know the type it has in each branch. Can we refactor otherwise? To get rid of the `unreachable`.

File: src/executor/insert.rs (hunk 1 above)
Comment (nitnelave) [reply src/executor/insert.rs:154]: Or even better, match `rows.pop()` with `None` -> `RecordNotInserted`

File: src/executor/insert.rs [hunk 3]
```diff
@@ -137,29 +138,49 @@ where
...
     };
+
     let last_insert_id = match primary_key {
-        Some(value_tuple) => FromValueTuple::from_value_tuple(value_tuple),
-        None => match last_insert_id_opt {
-            Some(last_insert_id) => last_insert_id,
-            None => return Err(DbErr::UnpackInsertId),
-        },
-    };
+        Some(value_tuple) => Ok(FromValueTuple::from_value_tuple(value_tuple)),
```
Comment (nitnelave) [inline src/executor/insert.rs:160]: It seems to be we just have to add a `db.execute(statement).await?` here rather than introduce an entirely new type.

File: src/executor/insert.rs [hunk 4]
```diff
@@ -137,29 +138,49 @@ where
...
+        None => {
+            if db.support_returning() {
+                match insert_result {
+                    QueryOrExecResult::Query(row) => {
+                        let cols = PrimaryKey::<A>::iter()
+                            .map(|col| col.to_string())
```
Comment (nitnelave) [inline src/executor/insert.rs:166]: That might be a bigger change, but I feel that `try_get_many` should accept a slice of `AsRef<str>` and `IdenStatic` should implement `AsRef<str>` so we don't have to do this whole conversion at all.

**Review by nitnelave — CHANGES_REQUESTED** [review]

**Comment by tyt2y3** [comment]
I don't see issues/1357 being run, but I assure it works on my machine(TM)

File: src/executor/insert.rs (hunk 4 above)
Comment (tyt2y3) [reply src/executor/insert.rs:166]: I agree, but that might be another PR

File: src/executor/insert.rs (hunk 3 above)
Comment (tyt2y3) [reply src/executor/insert.rs:160]: No. It has to execute whether Some or None.

File: src/executor/insert.rs (hunk 2 above)
Comment (tyt2y3) [reply src/executor/insert.rs:142]: I think the alternative is that we split the implementation.

File: src/executor/insert.rs (hunk 3 above)
Comment (nitnelave) [reply src/executor/insert.rs:160]: So, if we add the execute statement in the `Some` branch, we can inline the top of the function in the `None` branch, further reducing the amount of work done in case we provide the primary key. Each branch would have its own singular await point.

What's the rationale for reducing the number of await points?

File: src/executor/insert.rs (hunk 1 above)
Comment (tyt2y3) [reply src/executor/insert.rs]: Right

**Comment by tyt2y3** [comment]
Refactored. How about now?

File: src/executor/insert.rs [hunk 5]
```diff
@@ -137,29 +137,38 @@ where
...
-            let cols = PrimaryKey::<A>::iter()
-                .map(|col| col.to_string())
-                .collect::<Vec<_>>();
-            let rows = db.query_all(statement).await?;
-            let res = rows.last().ok_or_else(|| {
-                DbErr::RecordNotInserted("None of the records are being inserted".to_owned())
-            })?;
-            res.try_get_many("", cols.as_ref()).ok()
+
+    let last_insert_id = if db.support_returning() {
```
Comment (nitnelave) [inline src/executor/insert.rs:141]: That's much better! Do we absolutely care about `RecordNotInserted` if the primary key is provided? How can we detect it if the db doesn't support returning?

If we don't especially care about it, we could rewrite it as : 
```rust
match (primary_key, db.support_returning()) {
  (Some(value_tuple), _) => {db.execute(); Ok(FromValueTuple)},
  (None, true) =>{db.query_all() ... },
  (None, false) => {res = db.execute(); res.last_insert_id()},
}
```

WDYT?

Comment (tyt2y3) [reply src/executor/insert.rs:141]: Yes, I think we care. Because that's the case when we inserted a duplicate record?

> How can we detect it if the db doesn't support returning

Now it's a compile-time hardcoded value, with SQLite being false. Ideally, SQLite support should be determined by its version detected runtime.

Comment (nitnelave) [reply src/executor/insert.rs:141]: No, I mean how can we detect that the record was not inserted if the db doesn't support returning?

Comment (tyt2y3) [reply src/executor/insert.rs:141]: Umm, I see what you mean

Comment (nitnelave) [reply src/executor/insert.rs:141]: Could we use https://stackoverflow.com/questions/6551903/getting-the-number-of-affected-rows-for-a-sqlite-statement-using-the-c-api ?

Comment (nitnelave) [reply src/executor/insert.rs:141]: For sqlite, by calling `sqlite3_changes()` (or by selecting `changes()` in the query), we can get the number of rows affected. With that, we can see if it's 0 (didn't insert anything) or >0 (inserted at least one thing). That wouldn't catch the case where we insert >1 value but only some failed, but for single value inserts, it would already be helpful.

Comment (tyt2y3) [reply src/executor/insert.rs:141]: I think the code as of "Refactor" can be released in 0.10 and further changes should go into 0.11

Comment (nitnelave) [reply src/executor/insert.rs:141]: Sounds good. Just FYI, I tested `select changes();` on SQlite3, it seems to do what we want: after a single insert, it'll return 1 if the insert was successful, and 0 otherwise. And it's scoped to the DB connection as well, so it should be usable even in async contexts.

But anyway, inserting a single duplicate row returns an error, so probably the `await?` should trigger a return, no?

**Review by nitnelave — APPROVED** [review]

File: src/executor/insert.rs (hunk 5 above)
Comment (tyt2y3) [reply src/executor/insert.rs]: Yes. It should be a UNIQUE CONSTRAINT ERROR unless if we specified ON CONFLICT DO NOTHING.

File: src/executor/insert.rs [hunk 6]
```diff
@@ -137,29 +137,37 @@ where
 {
     type PrimaryKey<A> = <<A as ActiveModelTrait>::Entity as EntityTrait>::PrimaryKey;
     type ValueTypeOf<A> = <PrimaryKey<A> as PrimaryKeyTrait>::ValueType;
-    let last_insert_id_opt = match db.support_returning() {
-        true => {
+
+    let last_insert_id = match (primary_key, db.support_returning()) {
+        (Some(value_tuple), _) => {
+            let res = db.execute(statement).await?;
+            if res.rows_affected() == 0 {
```
Comment (nitnelave) [inline src/executor/insert.rs:144]: oh, if we have that, that's great!

**Review by nitnelave — APPROVED** [review]
Looks great!

File: src/executor/insert.rs [hunk 7]
```diff
@@ -137,29 +137,37 @@ where
 {
     type PrimaryKey<A> = <<A as ActiveModelTrait>::Entity as EntityTrait>::PrimaryKey;
     type ValueTypeOf<A> = <PrimaryKey<A> as PrimaryKeyTrait>::ValueType;
-    let last_insert_id_opt = match db.support_returning() {
-        true => {
+
+    let last_insert_id = match (primary_key, db.support_returning()) {
```
Comment (billy1624) [inline src/executor/insert.rs:141]: Nice rewrite!!

File: src/error.rs [hunk 8]
```diff
@@ -58,8 +58,8 @@ pub enum DbErr {
     /// None of the records are being inserted into the database,
     /// if you insert with upsert expression that means
     /// all of them conflict with existing records in the database
-    #[error("RecordNotInserted Error: {0}")]
-    RecordNotInserted(String),
+    #[error("None of the records are being inserted")]
+    RecordNotInserted,
```
Comment (billy1624) [inline src/error.rs:62]: I think this is a breaking change that should goes into 0.11.x

**Review by billy1624 — APPROVED** [review]

File: src/error.rs (hunk 8 above)
Comment (tyt2y3) [reply src/error.rs:62]: It's also not in 0.10 actually
